In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/ucl_2023_24.csv")

In [4]:
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,EC,05/08/2023,15:00,Aldershot,Oxford City,5,2,H,3,1,...,2.13,-0.75,2.00,1.80,2.06,1.79,2.08,1.85,1.99,1.77
1,EC,05/08/2023,15:00,Altrincham,Dag and Red,1,1,D,0,0,...,1.94,-0.25,1.68,2.15,1.75,2.12,1.96,2.19,1.73,2.05
2,EC,05/08/2023,15:00,Barnet,Hartlepool,3,2,H,1,0,...,2.05,-0.25,1.80,2.00,1.87,1.99,1.87,2.04,1.81,1.94
3,EC,05/08/2023,15:00,Chesterfield,Dorking,4,3,H,1,1,...,2.65,-2.00,1.88,1.93,1.98,1.86,1.98,1.93,1.90,1.84
4,EC,05/08/2023,15:00,Gateshead,Boreham Wood,2,2,D,2,0,...,1.78,-0.50,1.88,1.93,1.93,1.93,1.93,1.99,1.86,1.89

In [5]:
df.columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG', 'HTR', 'Referee', 'HY', 'AY', 'HR', 'AR', 'B365H',
       'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH',
       'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD',
       'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5',
       'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH',
       'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA',
       'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD',
       'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD',
       'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA',
       'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5',
       'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH',
       'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA'],
      dtype='str')

In [6]:
df.shape

(552, 98)

In [7]:
clean_df = df[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']]

In [8]:
clean_df.head()

         Date      HomeTeam      AwayTeam  FTHG  FTAG FTR
0  05/08/2023     Aldershot   Oxford City     5     2   H
1  05/08/2023    Altrincham   Dag and Red     1     1   D
2  05/08/2023        Barnet    Hartlepool     3     2   H
3  05/08/2023  Chesterfield       Dorking     4     3   H
4  05/08/2023     Gateshead  Boreham Wood     2     2   D

In [9]:
clean_df.shape

(552, 6)

In [10]:
clean_df.isnull().sum()

Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
dtype: int64

In [11]:
clean_df['Date'] = pd.to_datetime(clean_df['Date'], dayfirst=True)

In [12]:
clean_df = clean_df.sort_values(by='Date')

In [13]:
clean_df = clean_df.reset_index(drop=True)

In [14]:
clean_df.head()

        Date    HomeTeam     AwayTeam  FTHG  FTAG FTR
0 2023-08-05   Aldershot  Oxford City     5     2   H
1 2023-08-05    Rochdale    Ebbsfleet     0     1   A
2 2023-08-05  Wealdstone         York     2     1   H
3 2023-08-05    Southend       Oldham     4     0   H
4 2023-08-05  Maidenhead        Fylde     2     2   D

In [15]:
clean_df.shape

(552, 6)

In [16]:
import pandas as pd
from pathlib import Path

In [17]:
data_folder = Path("../data/raw")

In [18]:
files = [
    "ucl_2018_19.csv",
    "ucl_2019_20.csv",
    "ucl_2020_21.csv",
    "ucl_2021_22.csv",
    "ucl_2022_23.csv",
    "ucl_2023_24.csv"
]

In [19]:
season_dfs = []

In [20]:
for file in files:
    file_path = data_folder / file
    df = pd.read_csv(file_path, encoding='latin1')
    df = df[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']]
    df = df.dropna()
    df = df.drop_duplicates()
    df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
    season_dfs.append(df)

In [21]:
all_matches = pd.concat(season_dfs, ignore_index=True)

In [22]:
all_matches = all_matches.sort_values(by='Date').reset_index(drop=True)

In [23]:
all_matches.shape

(3090, 6)

In [24]:
all_matches.head()

        Date    HomeTeam       AwayTeam  FTHG  FTAG FTR
0 2018-08-04   Aldershot         Barnet     0     0   D
1 2018-08-04     Salford  Leyton Orient     1     1   D
2 2018-08-04   Maidstone     Hartlepool     1     1   D
3 2018-08-04  Maidenhead      Gateshead     1     3   A
4 2018-08-04       Fylde        Bromley     2     1   H

In [25]:
all_matches.tail()

           Date   HomeTeam    AwayTeam  FTHG  FTAG FTR
3085 2024-04-20  Gateshead     Bromley     2     1   H
3086 2024-04-20     Oldham  Wealdstone     2     3   A
3087 2024-04-20   Solihull        York     1     0   H
3088 2024-04-20   Southend    Rochdale     1     2   A
3089 2024-04-20     Woking       Fylde     3     0   H

In [26]:
all_matches.isnull().sum()

Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
dtype: int64

In [27]:
all_matches['FTR'].value_counts()

FTR
H    1316
A    1002
D     772
Name: count, dtype: int64

In [28]:
all_matches.to_csv("../data/combined_ucl_matches.csv", index=False)

In [29]:
df = pd.read_csv("../data/combined_ucl_matches.csv")

In [30]:
df['Date'] = pd.to_datetime(df['Date'])

In [31]:
df = df.sort_values(by='Date').reset_index(drop=True)

In [32]:
home_df = df[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']].copy()
home_df.columns = ['Date', 'Team', 'Opponent', 'GoalsFor', 'GoalsAgainst']

In [33]:
away_df = df[['Date', 'AwayTeam', 'HomeTeam', 'FTAG', 'FTHG']].copy()
away_df.columns = ['Date', 'Team', 'Opponent', 'GoalsFor', 'GoalsAgainst']

In [34]:
team_df = pd.concat([home_df, away_df], ignore_index=True)

In [35]:
team_df = team_df.sort_values(by='Date').reset_index(drop=True)

In [36]:
team_df.shape

(6180, 5)

In [37]:
team_df['Result'] = 0
team_df.loc[team_df['GoalsFor'] > team_df['GoalsAgainst'], 'Result'] = 1
team_df.loc[team_df['GoalsFor'] < team_df['GoalsAgainst'], 'Result'] = -1

In [38]:
team_df['Win'] = (team_df['Result'] == 1).astype(int)

In [39]:
team_df['GF_avg_last5'] = (
    team_df.groupby('Team')['GoalsFor']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

In [40]:
team_df['GA_avg_last5'] = (
    team_df.groupby('Team')['GoalsAgainst']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

In [41]:
team_df['Wins_last5'] = (
    team_df.groupby('Team')['Win']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).sum())
)

In [42]:
team_df[['Date', 'Team', 'GoalsFor', 'GoalsAgainst', 'Win', 'GF_avg_last5', 'Wins_last5']].head(15)

,Date,Team,GoalsFor,GoalsAgainst,Win,GF_avg_last5,Wins_last5
0,2018-08-04,Aldershot,0,0,0,NaN,NaN
1,2018-08-04,Hartlepool,1,1,0,NaN,NaN
2,2018-08-04,Gateshead,3,1,0,NaN,NaN
3,2018-08-04,Bromley,1,2,0,NaN,NaN
4,2018-08-04,Halifax,2,0,0,NaN,NaN
5,2018-08-04,Barnet,0,0,0,NaN,NaN
6,2018-08-04,Sutton,2,2,0,NaN,NaN
7,2018-08-04,Wrexham,1,0,0,NaN,NaN
8,2018-08-04,Dag and Red,0,1,0,NaN,NaN
9,2018-08-04,Havant & Waterlooville,0,3,0,NaN,NaN
10,2018-08-04,Solihull,2,1,0,NaN,NaN
11,2018-08-04,Chesterfield,1,0,0,NaN,NaN
12,2018-08-04,Leyton Orient,1,1,0,NaN,NaN
13,2018-08-04,Dover Athletic,0,1,0,NaN,NaN
14,2018-08-04,Maidstone,1,1,0,NaN,NaN

In [43]:
home_features = team_df[['Date', 'Team', 'GF_avg_last5', 'GA_avg_last5', 'Wins_last5']].copy()
home_features.columns = ['Date', 'HomeTeam', 'Home_GF_avg_last5', 'Home_GA_avg_last5', 'Home_Wins_last5']

In [44]:
away_features = team_df[['Date', 'Team', 'GF_avg_last5', 'GA_avg_last5', 'Wins_last5']].copy()
away_features.columns = ['Date', 'AwayTeam', 'Away_GF_avg_last5', 'Away_GA_avg_last5', 'Away_Wins_last5']

In [45]:
match_features = df.merge(home_features, on=['Date', 'HomeTeam'], how='left')

In [46]:
match_features = match_features.merge(away_features, on=['Date', 'AwayTeam'], how='left')

In [47]:
match_features.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,Home_GF_avg_last5,Home_GA_avg_last5,Home_Wins_last5,Away_GF_avg_last5,Away_GA_avg_last5,Away_Wins_last5
0,2018-08-04,Aldershot,Barnet,0,0,D,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-08-04,Eastleigh,Solihull,1,2,A,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-08-04,Barrow,Havant & Waterlooville,3,0,H,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-08-04,Boreham Wood,Dag and Red,1,0,H,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-08-04,Dover Athletic,Wrexham,0,1,A,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
match_features.columns

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'Home_GF_avg_last5', 'Home_GA_avg_last5', 'Home_Wins_last5',
       'Away_GF_avg_last5', 'Away_GA_avg_last5', 'Away_Wins_last5'],
      dtype='str')

In [49]:
match_features[['Home_GF_avg_last5', 'Home_GA_avg_last5', 'Home_Wins_last5', 'Away_GF_avg_last5', 'Away_GA_avg_last5', 'Away_Wins_last5']].isnull().sum()

Home_GF_avg_last5    23
Home_GA_avg_last5    23
Home_Wins_last5      23
Away_GF_avg_last5    20
Away_GA_avg_last5    20
Away_Wins_last5      20
dtype: int64

In [50]:
match_features.isnull().sum()

Date                  0
HomeTeam              0
AwayTeam              0
FTHG                  0
FTAG                  0
FTR                   0
Home_GF_avg_last5    23
Home_GA_avg_last5    23
Home_Wins_last5      23
Away_GF_avg_last5    20
Away_GA_avg_last5    20
Away_Wins_last5      20
dtype: int64

In [51]:
feature_cols = [
    'Home_GF_avg_last5', 'Home_GA_avg_last5', 'Home_Wins_last5', 'Away_GF_avg_last5', 'Away_GA_avg_last5', 'Away_Wins_last5'
]
match_features[feature_cols] = match_features[feature_cols].fillna(0)

In [52]:
model_df = match_features [['Date', 'HomeTeam', 'AwayTeam', 'Home_GF_avg_last5', 
                            'Home_GA_avg_last5', 'Home_Wins_last5', 'Away_GF_avg_last5', 'Away_GA_avg_last5', 'Away_Wins_last5', 'FTR']].copy()

In [53]:
model_df.head(
)

,Date,HomeTeam,AwayTeam,Home_GF_avg_last5,Home_GA_avg_last5,Home_Wins_last5,Away_GF_avg_last5,Away_GA_avg_last5,Away_Wins_last5,FTR
0,2018-08-04,Aldershot,Barnet,0.0,0.0,0.0,0.0,0.0,0.0,D
1,2018-08-04,Eastleigh,Solihull,0.0,0.0,0.0,0.0,0.0,0.0,A
2,2018-08-04,Barrow,Havant & Waterlooville,0.0,0.0,0.0,0.0,0.0,0.0,H
3,2018-08-04,Boreham Wood,Dag and Red,0.0,0.0,0.0,0.0,0.0,0.0,H
4,2018-08-04,Dover Athletic,Wrexham,0.0,0.0,0.0,0.0,0.0,0.0,A

In [54]:
model_df.shape

(3090, 10)

In [55]:
model_df['Target'] = model_df['FTR'].map({
    'H': 0,
    'D': 1,
    'A': 2
})

In [56]:
split_index = int(len(model_df) * 0.8)

train_df = model_df.iloc[:split_index]
test_df = model_df.iloc[split_index:]

In [57]:
match_features.columns
train_df.columns
model_df.columns

Index(['Date', 'HomeTeam', 'AwayTeam', 'Home_GF_avg_last5',
       'Home_GA_avg_last5', 'Home_Wins_last5', 'Away_GF_avg_last5',
       'Away_GA_avg_last5', 'Away_Wins_last5', 'FTR', 'Target'],
      dtype='str')

In [58]:
features = [    
    'Home_GF_avg_last5', 'Home_GA_avg_last5', 'Home_Wins_last5', 'Away_GF_avg_last5', 'Away_GA_avg_last5', 'Away_Wins_last5'
]
X_train = train_df[features]
y_train = train_df['Target']

X_test = test_df[features]
y_test = test_df['Target']

In [59]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [60]:
y_pred = model.predict(X_test)

In [62]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.35760517799352753

In [63]:
y_test.value_counts(normalize=True)

Target
0    0.419094
2    0.317152
1    0.263754
Name: proportion, dtype: float64

In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[128,  53,  78],
       [ 89,  23,  51],
       [ 98,  28,  70]])

In [66]:
model_df['GF_diff'] = model_df['Home_GF_avg_last5'] - model_df['Away_GF_avg_last5']
model_df['GA_diff'] = model_df['Home_GA_avg_last5'] - model_df['Away_GA_avg_last5']
model_df['Wins_diff'] = model_df['Home_Wins_last5'] - model_df['Away_Wins_last5']

In [71]:
features = [
    'Home_GF_avg_last5', 'Home_GA_avg_last5', 'Home_Wins_last5',
    'Away_GF_avg_last5', 'Away_GA_avg_last5', 'Away_Wins_last5',
    'GF_diff', 'GA_diff', 'Wins_diff' 
]

In [72]:
match_features.columns
train_df.columns
model_df.columns

Index(['Date', 'HomeTeam', 'AwayTeam', 'Home_GF_avg_last5',
       'Home_GA_avg_last5', 'Home_Wins_last5', 'Away_GF_avg_last5',
       'Away_GA_avg_last5', 'Away_Wins_last5', 'FTR', 'Target', 'GF_diff',
       'GA_diff', 'Wins_diff'],
      dtype='str')

In [74]:
train_df = model_df[model_df['Date'] < '2023-01-01']
test_df = model_df[model_df['Date'] >= '2023-01-01']

In [77]:
X_train = train_df[features]
y_train = train_df['Target']

X_test = test_df[features]
y_test = test_df['Target']

In [79]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [80]:
y_pred = model.predict(X_test)

In [82]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

confusion_matrix(y_test, y_pred)

Accuracy: 0.38331318016928656

array([[186,  69,  92],
       [107,  41,  65],
       [130,  47,  90]])